services:
  dnsmasq:
    image: 4km3/dnsmasq:latest
    container_name: pxe-dnsmasq
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./tftpboot:/var/lib/tftpboot:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "pgrep", "dnsmasq"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: pxe-nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./isos:/usr/share/nginx/html/isos:ro
      - ./config/templates:/usr/share/nginx/html/templates:ro
      - ./tftpboot:/usr/share/nginx/html/tftpboot:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:latest
    container_name: pxe-netbootxyz
    restart: unless-stopped
    ports:
      - "${WEB_INTERFACE_PORT:-3000}:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - MENU_VERSION=2.0.84
      - WEB_APP_PORT=3000
    volumes:
      - netbootxyz-config:/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  netbootxyz-config:
    driver: local

networks:
  default:
    name: pxe-network